# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vimage.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QToolBar, QVBoxLayout,
    QWidget)

from vmg.image_widget_gl import ImageWidgetGL

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(719, 577)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionExit.setMenuRole(QAction.QuitRole)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_As.setEnabled(False)
        self.actionNext = QAction(MainWindow)
        self.actionNext.setObjectName(u"actionNext")
        self.actionNext.setEnabled(False)
        icon = QIcon()
        icon.addFile(u"../images/next_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNext.setIcon(icon)
        self.actionPrevious = QAction(MainWindow)
        self.actionPrevious.setObjectName(u"actionPrevious")
        self.actionPrevious.setEnabled(False)
        icon1 = QIcon()
        icon1.addFile(u"../images/previous_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrevious.setIcon(icon1)
        self.actionSharp = QAction(MainWindow)
        self.actionSharp.setObjectName(u"actionSharp")
        self.actionSharp.setCheckable(True)
        self.actionSharp.setChecked(False)
        self.actionFull_Screen = QAction(MainWindow)
        self.actionFull_Screen.setObjectName(u"actionFull_Screen")
        self.actionFull_Screen.setCheckable(True)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout.setMenuRole(QAction.AboutRole)
        self.actionSave_Current_View_As = QAction(MainWindow)
        self.actionSave_Current_View_As.setObjectName(u"actionSave_Current_View_As")
        self.actionSave_Current_View_As.setEnabled(False)
        self.actionStereographic = QAction(MainWindow)
        self.actionStereographic.setObjectName(u"actionStereographic")
        self.actionStereographic.setCheckable(True)
        self.actionStereographic.setChecked(True)
        self.actionEquidistant = QAction(MainWindow)
        self.actionEquidistant.setObjectName(u"actionEquidistant")
        self.actionEquidistant.setCheckable(True)
        self.actionPerspective = QAction(MainWindow)
        self.actionPerspective.setObjectName(u"actionPerspective")
        self.actionPerspective.setCheckable(True)
        self.actionEquirectangular = QAction(MainWindow)
        self.actionEquirectangular.setObjectName(u"actionEquirectangular")
        self.actionEquirectangular.setCheckable(True)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionPaste.setEnabled(False)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionReset_View = QAction(MainWindow)
        self.actionReset_View.setObjectName(u"actionReset_View")
        self.actionReset_View.setEnabled(False)
        self.actionSelect_Rectangle = QAction(MainWindow)
        self.actionSelect_Rectangle.setObjectName(u"actionSelect_Rectangle")
        self.actionSelect_Rectangle.setEnabled(False)
        icon2 = QIcon()
        icon2.addFile(u"../images/box_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSelect_Rectangle.setIcon(icon2)
        self.actionCrop_to_Selection = QAction(MainWindow)
        self.actionCrop_to_Selection.setObjectName(u"actionCrop_to_Selection")
        self.actionCrop_to_Selection.setEnabled(False)
        self.actionCrop_to_Current_View = QAction(MainWindow)
        self.actionCrop_to_Current_View.setObjectName(u"actionCrop_to_Current_View")
        self.actionCrop_to_Current_View.setEnabled(False)
        self.actionSelect_None = QAction(MainWindow)
        self.actionSelect_None.setObjectName(u"actionSelect_None")
        self.actionSelect_None.setEnabled(False)
        self.actionZoom_Out = QAction(MainWindow)
        self.actionZoom_Out.setObjectName(u"actionZoom_Out")
        self.actionZoom_Out.setEnabled(True)
        icon3 = QIcon()
        icon3.addFile(u"../images/zoom_out.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoom_Out.setIcon(icon3)
        self.actionZoom_In = QAction(MainWindow)
        self.actionZoom_In.setObjectName(u"actionZoom_In")
        self.actionZoom_In.setEnabled(False)
        icon4 = QIcon()
        icon4.addFile(u"../images/zoom_in.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionZoom_In.setIcon(icon4)
        self.actionReport_a_Problem = QAction(MainWindow)
        self.actionReport_a_Problem.setObjectName(u"actionReport_a_Problem")
        self.actionReport_a_Problem.setEnabled(False)
        self.actionView_Log = QAction(MainWindow)
        self.actionView_Log.setObjectName(u"actionView_Log")
        self.actionPerspectiveInput = QAction(MainWindow)
        self.actionPerspectiveInput.setObjectName(u"actionPerspectiveInput")
        self.actionPerspectiveInput.setCheckable(True)
        self.actionPerspectiveInput.setChecked(True)
        self.actionEquirectangularInput = QAction(MainWindow)
        self.actionEquirectangularInput.setObjectName(u"actionEquirectangularInput")
        self.actionEquirectangularInput.setCheckable(True)
        self.actionDual_FisheyeInput = QAction(MainWindow)
        self.actionDual_FisheyeInput.setObjectName(u"actionDual_FisheyeInput")
        self.actionDual_FisheyeInput.setCheckable(True)
        self.actionConfigure_Dual_Fisheye = QAction(MainWindow)
        self.actionConfigure_Dual_Fisheye.setObjectName(u"actionConfigure_Dual_Fisheye")
        self.actionBrightnessPlus = QAction(MainWindow)
        self.actionBrightnessPlus.setObjectName(u"actionBrightnessPlus")
        self.actionBrightnessMinus = QAction(MainWindow)
        self.actionBrightnessMinus.setObjectName(u"actionBrightnessMinus")
        self.actionTile_Boundaries = QAction(MainWindow)
        self.actionTile_Boundaries.setObjectName(u"actionTile_Boundaries")
        self.actionTile_Boundaries.setCheckable(True)
        self.actionNearest = QAction(MainWindow)
        self.actionNearest.setObjectName(u"actionNearest")
        self.actionNearest.setCheckable(True)
        self.actionLinear = QAction(MainWindow)
        self.actionLinear.setObjectName(u"actionLinear")
        self.actionLinear.setCheckable(True)
        self.actionNearest_Mipmap_Nearest = QAction(MainWindow)
        self.actionNearest_Mipmap_Nearest.setObjectName(u"actionNearest_Mipmap_Nearest")
        self.actionNearest_Mipmap_Nearest.setCheckable(True)
        self.actionLinear_Mipmap_Nearest = QAction(MainWindow)
        self.actionLinear_Mipmap_Nearest.setObjectName(u"actionLinear_Mipmap_Nearest")
        self.actionLinear_Mipmap_Nearest.setCheckable(True)
        self.actionNearest_Mipmap_Linear = QAction(MainWindow)
        self.actionNearest_Mipmap_Linear.setObjectName(u"actionNearest_Mipmap_Linear")
        self.actionNearest_Mipmap_Linear.setCheckable(True)
        self.actionLinear_Mipmap_Linear = QAction(MainWindow)
        self.actionLinear_Mipmap_Linear.setObjectName(u"actionLinear_Mipmap_Linear")
        self.actionLinear_Mipmap_Linear.setCheckable(True)
        self.actionLinear_Mipmap_Linear.setChecked(True)
        self.actionNearest_2 = QAction(MainWindow)
        self.actionNearest_2.setObjectName(u"actionNearest_2")
        self.actionNearest_2.setCheckable(True)
        self.actionNearest_2.setChecked(False)
        self.actionLinear_2 = QAction(MainWindow)
        self.actionLinear_2.setObjectName(u"actionLinear_2")
        self.actionLinear_2.setCheckable(True)
        self.actionClamp_To_Edge = QAction(MainWindow)
        self.actionClamp_To_Edge.setObjectName(u"actionClamp_To_Edge")
        self.actionClamp_To_Edge.setCheckable(True)
        self.actionClamp_To_Edge.setChecked(True)
        self.actionClamp_To_Border = QAction(MainWindow)
        self.actionClamp_To_Border.setObjectName(u"actionClamp_To_Border")
        self.actionClamp_To_Border.setCheckable(True)
        self.actionMirrored_Repeat = QAction(MainWindow)
        self.actionMirrored_Repeat.setObjectName(u"actionMirrored_Repeat")
        self.actionMirrored_Repeat.setCheckable(True)
        self.actionRepeat = QAction(MainWindow)
        self.actionRepeat.setObjectName(u"actionRepeat")
        self.actionRepeat.setCheckable(True)
        self.actionMirror_Clamp_To_Edge = QAction(MainWindow)
        self.actionMirror_Clamp_To_Edge.setObjectName(u"actionMirror_Clamp_To_Edge")
        self.actionMirror_Clamp_To_Edge.setCheckable(True)
        self.actionAnisotropic_Filtering = QAction(MainWindow)
        self.actionAnisotropic_Filtering.setObjectName(u"actionAnisotropic_Filtering")
        self.actionAnisotropic_Filtering.setCheckable(True)
        self.actionAnisotropic_Filtering.setChecked(True)
        self.actionCatmull_Rom = QAction(MainWindow)
        self.actionCatmull_Rom.setObjectName(u"actionCatmull_Rom")
        self.actionCatmull_Rom.setCheckable(True)
        self.actionCatmull_Rom.setChecked(True)
        self.actionClamp_To_Edge_2 = QAction(MainWindow)
        self.actionClamp_To_Edge_2.setObjectName(u"actionClamp_To_Edge_2")
        self.actionClamp_To_Border_2 = QAction(MainWindow)
        self.actionClamp_To_Border_2.setObjectName(u"actionClamp_To_Border_2")
        self.actionMirrored_Repeat_2 = QAction(MainWindow)
        self.actionMirrored_Repeat_2.setObjectName(u"actionMirrored_Repeat_2")
        self.actionRepeat_2 = QAction(MainWindow)
        self.actionRepeat_2.setObjectName(u"actionRepeat_2")
        self.actionMirror_Clamp_To_Edge_2 = QAction(MainWindow)
        self.actionMirror_Clamp_To_Edge_2.setObjectName(u"actionMirror_Clamp_To_Edge_2")
        self.actionDecrease_LOD_Bias = QAction(MainWindow)
        self.actionDecrease_LOD_Bias.setObjectName(u"actionDecrease_LOD_Bias")
        self.actionIncrease_LOD_Bias = QAction(MainWindow)
        self.actionIncrease_LOD_Bias.setObjectName(u"actionIncrease_LOD_Bias")
        self.actionHexadecimal = QAction(MainWindow)
        self.actionHexadecimal.setObjectName(u"actionHexadecimal")
        self.actionHexadecimal.setCheckable(True)
        self.actionHexadecimal.setChecked(True)
        self.actionDecimal = QAction(MainWindow)
        self.actionDecimal.setObjectName(u"actionDecimal")
        self.actionDecimal.setCheckable(True)
        self.actionNone = QAction(MainWindow)
        self.actionNone.setObjectName(u"actionNone")
        self.actionNone.setCheckable(True)
        self.actionSinusoidalInput = QAction(MainWindow)
        self.actionSinusoidalInput.setObjectName(u"actionSinusoidalInput")
        self.actionSinusoidalInput.setCheckable(True)
        self.actionShow_Center_Guides = QAction(MainWindow)
        self.actionShow_Center_Guides.setObjectName(u"actionShow_Center_Guides")
        self.actionShow_Center_Guides.setCheckable(True)
        self.actionFoo = QAction(MainWindow)
        self.actionFoo.setObjectName(u"actionFoo")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.imageWidgetGL = ImageWidgetGL(self.centralwidget)
        self.imageWidgetGL.setObjectName(u"imageWidgetGL")
        self.imageWidgetGL.setFocusPolicy(Qt.StrongFocus)

        self.verticalLayout.addWidget(self.imageWidgetGL)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 719, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuOpen_Recent = QMenu(self.menuFile)
        self.menuOpen_Recent.setObjectName(u"menuOpen_Recent")
        self.menuRecent_Folders = QMenu(self.menuFile)
        self.menuRecent_Folders.setObjectName(u"menuRecent_Folders")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menu360_Projection = QMenu(self.menuView)
        self.menu360_Projection.setObjectName(u"menu360_Projection")
        self.menu360_Projection.setEnabled(False)
        self.menuInput_Projection = QMenu(self.menuView)
        self.menuInput_Projection.setObjectName(u"menuInput_Projection")
        self.menuDebug = QMenu(self.menuView)
        self.menuDebug.setObjectName(u"menuDebug")
        self.menuTexture_Min_Filter = QMenu(self.menuDebug)
        self.menuTexture_Min_Filter.setObjectName(u"menuTexture_Min_Filter")
        self.menuTexture_Mag_Filter = QMenu(self.menuDebug)
        self.menuTexture_Mag_Filter.setObjectName(u"menuTexture_Mag_Filter")
        self.menuTexture_Wrap_Horizontal = QMenu(self.menuDebug)
        self.menuTexture_Wrap_Horizontal.setObjectName(u"menuTexture_Wrap_Horizontal")
        self.menuTexture_LOD_Bias = QMenu(self.menuDebug)
        self.menuTexture_LOD_Bias.setObjectName(u"menuTexture_LOD_Bias")
        self.menuZoom = QMenu(self.menuView)
        self.menuZoom.setObjectName(u"menuZoom")
        self.menuBrightness = QMenu(self.menuView)
        self.menuBrightness.setObjectName(u"menuBrightness")
        self.menuPixel_Values = QMenu(self.menuView)
        self.menuPixel_Values.setObjectName(u"menuPixel_Values")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuOpen_Recent.menuAction())
        self.menuFile.addAction(self.menuRecent_Folders.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_Current_View_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionReset_View)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuZoom.menuAction())
        self.menuView.addAction(self.menuBrightness.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionPrevious)
        self.menuView.addAction(self.actionNext)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFull_Screen)
        self.menuView.addAction(self.menuPixel_Values.menuAction())
        self.menuView.addAction(self.actionSharp)
        self.menuView.addAction(self.actionShow_Center_Guides)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menu360_Projection.menuAction())
        self.menuView.addAction(self.menuInput_Projection.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionView_Log)
        self.menuView.addAction(self.menuDebug.menuAction())
        self.menu360_Projection.addAction(self.actionPerspective)
        self.menu360_Projection.addAction(self.actionStereographic)
        self.menu360_Projection.addAction(self.actionEquidistant)
        self.menu360_Projection.addAction(self.actionEquirectangular)
        self.menuInput_Projection.addAction(self.actionPerspectiveInput)
        self.menuInput_Projection.addAction(self.actionEquirectangularInput)
        self.menuInput_Projection.addAction(self.actionSinusoidalInput)
        self.menuInput_Projection.addAction(self.actionDual_FisheyeInput)
        self.menuInput_Projection.addSeparator()
        self.menuDebug.addAction(self.actionTile_Boundaries)
        self.menuDebug.addAction(self.actionAnisotropic_Filtering)
        self.menuDebug.addAction(self.menuTexture_Min_Filter.menuAction())
        self.menuDebug.addAction(self.menuTexture_Mag_Filter.menuAction())
        self.menuDebug.addAction(self.menuTexture_Wrap_Horizontal.menuAction())
        self.menuDebug.addAction(self.menuTexture_LOD_Bias.menuAction())
        self.menuTexture_Min_Filter.addAction(self.actionNearest)
        self.menuTexture_Min_Filter.addAction(self.actionLinear)
        self.menuTexture_Min_Filter.addAction(self.actionNearest_Mipmap_Nearest)
        self.menuTexture_Min_Filter.addAction(self.actionLinear_Mipmap_Nearest)
        self.menuTexture_Min_Filter.addAction(self.actionNearest_Mipmap_Linear)
        self.menuTexture_Min_Filter.addAction(self.actionLinear_Mipmap_Linear)
        self.menuTexture_Mag_Filter.addAction(self.actionNearest_2)
        self.menuTexture_Mag_Filter.addAction(self.actionLinear_2)
        self.menuTexture_Mag_Filter.addAction(self.actionCatmull_Rom)
        self.menuTexture_Wrap_Horizontal.addAction(self.actionClamp_To_Edge)
        self.menuTexture_Wrap_Horizontal.addAction(self.actionClamp_To_Border)
        self.menuTexture_Wrap_Horizontal.addAction(self.actionMirrored_Repeat)
        self.menuTexture_Wrap_Horizontal.addAction(self.actionRepeat)
        self.menuTexture_Wrap_Horizontal.addAction(self.actionMirror_Clamp_To_Edge)
        self.menuTexture_LOD_Bias.addAction(self.actionDecrease_LOD_Bias)
        self.menuTexture_LOD_Bias.addAction(self.actionIncrease_LOD_Bias)
        self.menuZoom.addAction(self.actionZoom_In)
        self.menuZoom.addAction(self.actionZoom_Out)
        self.menuBrightness.addAction(self.actionBrightnessMinus)
        self.menuBrightness.addAction(self.actionBrightnessPlus)
        self.menuPixel_Values.addAction(self.actionHexadecimal)
        self.menuPixel_Values.addAction(self.actionDecimal)
        self.menuPixel_Values.addAction(self.actionNone)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionReport_a_Problem)
        self.menuEdit.addAction(self.actionCrop_to_Current_View)
        self.menuEdit.addAction(self.actionCrop_to_Selection)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSelect_Rectangle)
        self.menuEdit.addAction(self.actionSelect_None)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionConfigure_Dual_Fisheye)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrevious)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_In)
        self.toolBar.addAction(self.actionZoom_Out)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.actionNext.setText(QCoreApplication.translate("MainWindow", u"Next Image", None))
#if QT_CONFIG(shortcut)
        self.actionNext.setShortcut(QCoreApplication.translate("MainWindow", u"Right", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrevious.setText(QCoreApplication.translate("MainWindow", u"Previous Image", None))
#if QT_CONFIG(shortcut)
        self.actionPrevious.setShortcut(QCoreApplication.translate("MainWindow", u"Left", None))
#endif // QT_CONFIG(shortcut)
        self.actionSharp.setText(QCoreApplication.translate("MainWindow", u"Sharp Pixels", None))
#if QT_CONFIG(shortcut)
        self.actionSharp.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.actionFull_Screen.setText(QCoreApplication.translate("MainWindow", u"Full Screen", None))
#if QT_CONFIG(shortcut)
        self.actionFull_Screen.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionSave_Current_View_As.setText(QCoreApplication.translate("MainWindow", u"Save Current View As...", None))
        self.actionStereographic.setText(QCoreApplication.translate("MainWindow", u"Stereographic", None))
#if QT_CONFIG(tooltip)
        self.actionStereographic.setToolTip(QCoreApplication.translate("MainWindow", u"Stereographic projection preserves the shapes and angles of objects. This can be used to make \"small world\" images. The image is unbounded and the field of view is limited to less than 360 degrees.", None))
#endif // QT_CONFIG(tooltip)
        self.actionEquidistant.setText(QCoreApplication.translate("MainWindow", u"Equidistant", None))
#if QT_CONFIG(tooltip)
        self.actionEquidistant.setToolTip(QCoreApplication.translate("MainWindow", u"Equidistant projection can show the entire panorama within a circular boundary. Distances from the center point are proportional to the true angle from the center point.", None))
#endif // QT_CONFIG(tooltip)
        self.actionPerspective.setText(QCoreApplication.translate("MainWindow", u"Perspective", None))
#if QT_CONFIG(tooltip)
        self.actionPerspective.setToolTip(QCoreApplication.translate("MainWindow", u"Perspective projection is similar to plain old non-360 non-fisheye photos. Straight lines in the real world remain straight in this projection. The image is unbounded and the field of view is limited to less than 180 degrees.", None))
#endif // QT_CONFIG(tooltip)
        self.actionEquirectangular.setText(QCoreApplication.translate("MainWindow", u"Equirectangular", None))
#if QT_CONFIG(tooltip)
        self.actionEquirectangular.setToolTip(QCoreApplication.translate("MainWindow", u"Equirectangular projection can show the entire panorama within a rectangle. This projection is often used as the internal storage format for 360 images.", None))
#endif // QT_CONFIG(tooltip)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionReset_View.setText(QCoreApplication.translate("MainWindow", u"Reset View", None))
        self.actionSelect_Rectangle.setText(QCoreApplication.translate("MainWindow", u"Select Rectangle", None))
#if QT_CONFIG(tooltip)
        self.actionSelect_Rectangle.setToolTip(QCoreApplication.translate("MainWindow", u"Select a rectangular region", None))
#endif // QT_CONFIG(tooltip)
        self.actionCrop_to_Selection.setText(QCoreApplication.translate("MainWindow", u"Crop to Selection", None))
        self.actionCrop_to_Current_View.setText(QCoreApplication.translate("MainWindow", u"Crop to Current View", None))
        self.actionSelect_None.setText(QCoreApplication.translate("MainWindow", u"Select None", None))
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
#if QT_CONFIG(shortcut)
        self.actionZoom_Out.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionZoom_In.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
#if QT_CONFIG(shortcut)
        self.actionZoom_In.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+=", None))
#endif // QT_CONFIG(shortcut)
        self.actionReport_a_Problem.setText(QCoreApplication.translate("MainWindow", u"Report a Problem...", None))
        self.actionView_Log.setText(QCoreApplication.translate("MainWindow", u"View Log", None))
        self.actionPerspectiveInput.setText(QCoreApplication.translate("MainWindow", u"Standard Photo", None))
        self.actionEquirectangularInput.setText(QCoreApplication.translate("MainWindow", u"Equirectangular", None))
        self.actionDual_FisheyeInput.setText(QCoreApplication.translate("MainWindow", u"Dual Fisheye", None))
        self.actionConfigure_Dual_Fisheye.setText(QCoreApplication.translate("MainWindow", u"Camera Settings...", None))
        self.actionBrightnessPlus.setText(QCoreApplication.translate("MainWindow", u"Brightness+", None))
#if QT_CONFIG(shortcut)
        self.actionBrightnessPlus.setShortcut(QCoreApplication.translate("MainWindow", u"]", None))
#endif // QT_CONFIG(shortcut)
        self.actionBrightnessMinus.setText(QCoreApplication.translate("MainWindow", u"Brightness-", None))
#if QT_CONFIG(shortcut)
        self.actionBrightnessMinus.setShortcut(QCoreApplication.translate("MainWindow", u"[", None))
#endif // QT_CONFIG(shortcut)
        self.actionTile_Boundaries.setText(QCoreApplication.translate("MainWindow", u"Show Tile Boundaries", None))
#if QT_CONFIG(shortcut)
        self.actionTile_Boundaries.setShortcut(QCoreApplication.translate("MainWindow", u"B", None))
#endif // QT_CONFIG(shortcut)
        self.actionNearest.setText(QCoreApplication.translate("MainWindow", u"Nearest", None))
        self.actionLinear.setText(QCoreApplication.translate("MainWindow", u"Linear", None))
        self.actionNearest_Mipmap_Nearest.setText(QCoreApplication.translate("MainWindow", u"Nearest, Mipmap Nearest", None))
        self.actionLinear_Mipmap_Nearest.setText(QCoreApplication.translate("MainWindow", u"Linear, Mipmap Nearest", None))
        self.actionNearest_Mipmap_Linear.setText(QCoreApplication.translate("MainWindow", u"Nearest, Mipmap Linear", None))
        self.actionLinear_Mipmap_Linear.setText(QCoreApplication.translate("MainWindow", u"Linear, Mipmap Linear", None))
        self.actionNearest_2.setText(QCoreApplication.translate("MainWindow", u"Nearest", None))
        self.actionLinear_2.setText(QCoreApplication.translate("MainWindow", u"Linear", None))
        self.actionClamp_To_Edge.setText(QCoreApplication.translate("MainWindow", u"Clamp To Edge", None))
        self.actionClamp_To_Border.setText(QCoreApplication.translate("MainWindow", u"Clamp To Border", None))
        self.actionMirrored_Repeat.setText(QCoreApplication.translate("MainWindow", u"Mirrored Repeat", None))
        self.actionRepeat.setText(QCoreApplication.translate("MainWindow", u"Repeat", None))
        self.actionMirror_Clamp_To_Edge.setText(QCoreApplication.translate("MainWindow", u"Mirror Clamp To Edge", None))
        self.actionAnisotropic_Filtering.setText(QCoreApplication.translate("MainWindow", u"Anisotropic Filtering", None))
#if QT_CONFIG(shortcut)
        self.actionAnisotropic_Filtering.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.actionCatmull_Rom.setText(QCoreApplication.translate("MainWindow", u"Catmull Rom", None))
        self.actionClamp_To_Edge_2.setText(QCoreApplication.translate("MainWindow", u"Clamp To Edge", None))
        self.actionClamp_To_Border_2.setText(QCoreApplication.translate("MainWindow", u"Clamp To Border", None))
        self.actionMirrored_Repeat_2.setText(QCoreApplication.translate("MainWindow", u"Mirrored Repeat", None))
        self.actionRepeat_2.setText(QCoreApplication.translate("MainWindow", u"Repeat", None))
        self.actionMirror_Clamp_To_Edge_2.setText(QCoreApplication.translate("MainWindow", u"Mirror Clamp To Edge", None))
        self.actionDecrease_LOD_Bias.setText(QCoreApplication.translate("MainWindow", u"Decrease LOD Bias", None))
        self.actionIncrease_LOD_Bias.setText(QCoreApplication.translate("MainWindow", u"Increase LOD Bias", None))
        self.actionHexadecimal.setText(QCoreApplication.translate("MainWindow", u"Hexadecimal", None))
        self.actionDecimal.setText(QCoreApplication.translate("MainWindow", u"Decimal", None))
        self.actionNone.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.actionSinusoidalInput.setText(QCoreApplication.translate("MainWindow", u"Sinusoidal", None))
        self.actionShow_Center_Guides.setText(QCoreApplication.translate("MainWindow", u"Show Center Guides", None))
#if QT_CONFIG(shortcut)
        self.actionShow_Center_Guides.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.actionFoo.setText(QCoreApplication.translate("MainWindow", u"Foo", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuOpen_Recent.setTitle(QCoreApplication.translate("MainWindow", u"Open Recent", None))
        self.menuRecent_Folders.setTitle(QCoreApplication.translate("MainWindow", u"Recent Folders...", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menu360_Projection.setTitle(QCoreApplication.translate("MainWindow", u"Display Projection", None))
        self.menuInput_Projection.setTitle(QCoreApplication.translate("MainWindow", u"Input Format", None))
        self.menuDebug.setTitle(QCoreApplication.translate("MainWindow", u"Debug", None))
        self.menuTexture_Min_Filter.setTitle(QCoreApplication.translate("MainWindow", u"Texture Min Filter", None))
        self.menuTexture_Mag_Filter.setTitle(QCoreApplication.translate("MainWindow", u"Texture Mag Filter", None))
        self.menuTexture_Wrap_Horizontal.setTitle(QCoreApplication.translate("MainWindow", u"Texture Wrap", None))
        self.menuTexture_LOD_Bias.setTitle(QCoreApplication.translate("MainWindow", u"Texture LOD Bias", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.menuBrightness.setTitle(QCoreApplication.translate("MainWindow", u"Brightness", None))
        self.menuPixel_Values.setTitle(QCoreApplication.translate("MainWindow", u"Pixel Values", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        pass
    # retranslateUi

